.TH cqemu 1 "01 26 2025" "herneri's shell scripts" "User commands"
.SH NAME
cqemu \- Create and run a Qemu KVM

.SH SYNOPSIS
cqemu [KVM_NAME] [ISO_FILE] [DISK_SIZE] [RAM_SIZE]

.SH DESCRIPTION
Creates and runs a Qemu KVM using the given specifications from the CLI.

.SH EXIT STATUS
.LP
0: Successful operation.
.TP
1: Missing one or more arguments.

.SH AUTHOR
Eric Hernandez (herneri@protonmail.com)
