.TH findgit 1 "01 26 2025" "herneri's shell scripts" "User commands"
.SH NAME
findgit \- List all Git repositories within the home directory.

.SH SYNOPSIS
findgit

.SH DESCRIPTION
All child directories are searched for whether they contain Git reposistories.
Redundant information like the path to home and the .git directory are omitted from
the listing.

.SH AUTHOR
Eric Hernandez (herneri@protonmail.com)
